### ISSUE TITLE
Exception when trying to open PDF

### ISSUE THREAD

**Issue by npcnixel** [UnityTheCoder/BookTUI#1]
Basically,  when trying to open any O'reilly book, I catch this exception.

![image](https://user-images.githubusercontent.com/44145910/183521816-4960f7bf-7163-450a-849e-e4c3b4f8e455.png)

**Comment by utcq** [comment]
this mean that your pdf file isn't supported, Adding an exception handler soon

edit: I opened several O'reilly books and they all worked, so I think it's a problem with your file

**Comment by utcq** [comment]
btw update to the newset version, i've fixed a lot of bugs and implemented some interessing features
